id: IA7400770
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:56:37.813744
last_modified: 2023-02-09 14:56:37.813850
source_metadata:
  title: 'RK: Gaṅgottaraparipṛcchā'
  language: zh
bases:
  B250:
    base_file: B250.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
